export const FILTERTODO = "FILTERTODO";
export const CLEARTODO = "CLEARTODO";
export const DELETETODO = "DELETETODO";
export const COMPLETEDTODO = "COMPLETEDTODO";
export const ADDTODO = "ADDTODO";
export const SHOWCOMPLETED = "SHOWCOMPLETED";
export const CLEARCOMPLETED = "CLEARCOMPLETED";
